apiVersion: v1
kind: ServiceAccount
metadata:
  name: goserver # Mesmo nome do deployment

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: goserver-read
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goserver-read-binding
subjects:
- kind: ServiceAccount
  name: goserver # ServiceAccount name created above
  namespace: default
roleRef:
  kind: Role
  name: goserver-read
  apiGroup: rbac.authorization.k8s.io